import keyMirror from 'keyMirror';

const AppConstants = {
    AJAX_START: 'AJAX_START',
    AJAX_END: 'AJAX_END',
    GRAB_LOCATION: 'GRAB_LOCATION',
    FETCH_WEATHER: 'FETCH_WEATHER',
    SET_LOCATION: 'SET_LOCATION',
    SHOW_TOAST: 'SHOW_TOAST',
    RECIEVE_WEATHER: 'RECIEVE_WEATHER',
    SET_LOCATION_NAME: 'SET_LOCATION_NAME'
}

export default AppConstants;
